import type { Metadata } from 'next';
import './globals.css';
import Sidebar from './components/Sidebar/Sidebar';
import Header from './components/Header/Header';
import Footer from './components/Footer/Footer';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="flex h-screen">
          <Sidebar />
          <div className="flex flex-col flex-1">
            <Header title="My React Playground" />
            <main className="flex-1 overflow-y-auto p-4">{children}</main>
            <Footer title="React Playground 2025" />
          </div>
        </div>
      </body>
    </html>
  );
}
